[package]
name = "ray-tracing"
version = "0.1.0"
authors = ["sousei <inadakoro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
nalgebra = "*"

[lib]
name = "renderer"
path = "src/lib.rs"
